import type { Metadata } from "next";

import { Geist, Geist_Mono } from "next/font/google";
import NavBar from "@/features/layout/nav-bar";
import { getI18nConfig } from "@/i18n-config";
import Footer from "@/features/layout/footer";
import { Toaster } from "@/components/ui/sonner";
import AppProviders from "@/features/app-providers";

import "./globals.css";

export const generateStaticParams = async () => {
  const { locales } = await getI18nConfig();

  return locales.map((locale) => ({
    locale: locale,
  }));
};
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Contentful Example",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Root layout doesn't have access to locale params - use default
  const { defaultLocale } = await getI18nConfig();
  return (
    <html lang={defaultLocale}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AppProviders>
          <NavBar />
          {children}
          <Toaster />
          <Footer />
        </AppProviders>
      </body>
    </html>
  );
}
