import type { Metadata } from "next";

import { getI18nConfig, type Locale } from "@/i18n-config";

// import "./globals.css";

export const generateStaticParams = async () => {
  const { locales } = await getI18nConfig();

  return locales.map((locale) => ({
    locale: locale,
  }));
};

export const metadata: Metadata = {
  title: "Contentful Example",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: Locale; preview: string }>;
}>) {
  const { locale } = await params;

  return <div lang={locale}>{children}</div>;
}
